# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170313_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
